/**************************************************************************************************
 Filename:       zrc_app_log_constants.c

 Description:    Constants used for verbose logging

   Copyright (C) 2015 Texas Instruments Incorporated - http://www.ti.com/


   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

     Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.

     Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the
     distribution.

     Neither the name of Texas Instruments Incorporated nor the names of
     its contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**************************************************************************************************/

#ifndef ZRC_APP_LOG_CONSTANTS_H
#define ZRC_APP_LOG_CONSTANTS_H

#include "stddef.h"
#include "zrc_app_log_constants.h"

const char * const rtiStatus_list[256] =
{
        NAME_ELEMENT(RTI_SUCCESS),
        NAME_ELEMENT(RTI_ERROR_INVALID_INDEX),
        NAME_ELEMENT(RTI_ERROR_INVALID_PARAMETER),
        NAME_ELEMENT(RTI_ERROR_UNSUPPORTED_ATTRIBUTE),
        NAME_ELEMENT(RTI_ERROR_NO_ORG_CAPACITY),                        //0xB0
        NAME_ELEMENT(RTI_ERROR_NO_REC_CAPACITY),                        //0xB1
        NAME_ELEMENT(RTI_ERROR_NO_PAIRING_INDEX),                       //0xB2
        NAME_ELEMENT(RTI_ERROR_NO_RESPONSE),                            //0xB3
        NAME_ELEMENT(RTI_ERROR_NOT_PERMITTED),                          //0xB4
        NAME_ELEMENT(RTI_ERROR_FRAME_COUNTER_EXPIRED),                  //0xB6
        NAME_ELEMENT(RTI_ERROR_DISCOVERY_ERROR),                        //0xB7
        NAME_ELEMENT(RTI_ERROR_DISCOVERY_TIMEOUT),                      //0xB8
        NAME_ELEMENT(RTI_ERROR_SECURITY_TIMEOUT),                       //0xB9
        NAME_ELEMENT(RTI_ERROR_SECURITY_FAILURE),                       //0xBA
        NAME_ELEMENT(RTI_ERROR_NO_SECURITY_KEY),                        //0xBD
        NAME_ELEMENT(RTI_ERROR_OUT_OF_MEMORY),                          //0xBE
        NAME_ELEMENT(RTI_ERROR_OSAL_NO_TIMER_AVAIL),                    //0x08
        NAME_ELEMENT(RTI_ERROR_OSAL_NV_OPER_FAILED),                    //0x0A
        NAME_ELEMENT(RTI_ERROR_OSAL_NV_ITEM_UNINIT),                    //0x09
        NAME_ELEMENT(RTI_ERROR_OSAL_NV_BAD_ITEM_LEN),                   //0x0C
        NAME_ELEMENT(RTI_ERROR_MAC_TRANSACTION_EXPIRED),                //0xF0
        NAME_ELEMENT(RTI_ERROR_MAC_TRANSACTION_OVERFLOW),               //0xF1
        NAME_ELEMENT(RTI_ERROR_MAC_NO_RESOURCES),                       //0x1A
        NAME_ELEMENT(RTI_ERROR_MAC_UNSUPPORTED),                        //0x18
        NAME_ELEMENT(RTI_ERROR_MAC_BAD_STATE),                          //0x19
        NAME_ELEMENT(RTI_ERROR_MAC_CHANNEL_ACCESS_FAILURE),             //0xE1
        NAME_ELEMENT(RTI_ERROR_MAC_NO_ACK),                             //0xE9
        NAME_ELEMENT(RTI_ERROR_MAC_BEACON_LOST),                        //0xE0
        NAME_ELEMENT(RTI_ERROR_MAC_PAN_ID_CONFLICT),                    //0xEE
        NAME_ELEMENT(RTI_ERROR_MAC_SCAN_IN_PROGRESS),                   //0xFC
        NAME_ELEMENT(RTI_ERROR_UNKNOWN_STATUS_RETURNED),                //0x20
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_DISCOVER),                     //0x21
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_PAIR),                         //0x22
        NAME_ELEMENT(RTI_ERROR_ALLOW_PAIRING_TIMEOUT),                  //0x23
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_ZRC_OLD),            //0x41
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_ZID_OLD),            //0x42
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_Z3D),                //0x43
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_INV_MASK),           //(0x40)
  // reserve failure IDs 0x44-0x4A for future profiles
        NAME_ELEMENT(RTI_ERROR_SYNCHRONOUS_NPI_TIMEOUT),                //0xFF
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_ZRC),                //0x50
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_ZID),                //0x51
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_ZRC20),              //0x52
        NAME_ELEMENT(RTI_ERROR_FAILED_TO_CONFIGURE_INV_MASK),           //(0x50)
        NAME_ELEMENT(RTI_ERROR_VALIDATION_FAILURE),                     //0x53
        NAME_ELEMENT(RTI_ERROR_BINDING_TIMEOUT),                        //0x54
        NAME_ELEMENT(RTI_ERROR_NO_POLLING_CONFIG),                      //0x55
        NAME_ELEMENT(RTI_ERROR_ENHANCED_SECURITY_TIMEOUT),              //0x56
        NAME_ELEMENT(RTI_ERROR_NO_PROXY_DEVICE),                        //0x57
        NAME_ELEMENT(RTI_ERROR_ENHANCED_SECURITY_NOT_SUPPORTED),        //0x58
        NAME_ELEMENT(RTI_ERROR_ATTRIBUTE_REQUEST_BUSY),                 //0x59
		NAME_ELEMENT(RTI_ERROR_SYNCHRONOUS_NPI_TIMEOUT),                //0xFF
};

const char * const rtiProfileId_list[RTI_PROFILE_RTI + 1] =
{
		[0 ... RTI_PROFILE_RTI] = NULL,
		NAME_ELEMENT(RTI_PROFILE_GDP),
		NAME_ELEMENT(RTI_PROFILE_ZRC),
		NAME_ELEMENT(RTI_PROFILE_ZID),
		NAME_ELEMENT(RTI_PROFILE_ZRC20),
		NAME_ELEMENT(RTI_PROFILE_TI),
		NAME_ELEMENT(RTI_PROFILE_MSO),
		NAME_ELEMENT(RTI_PROFILE_TOAD)
};

const char * const rtiVendorId_list[RTI_VENDOR_TEXAS_INSTRUMENTS + 1] =
{
		[0 ... RTI_VENDOR_TEXAS_INSTRUMENTS] = NULL,
		NAME_ELEMENT(RTI_VENDOR_PANASONIC),
		NAME_ELEMENT(RTI_VENDOR_SONY),
		NAME_ELEMENT(RTI_VENDOR_SAMSUNG),
		NAME_ELEMENT(RTI_VENDOR_PHILIPS),
		NAME_ELEMENT(RTI_VENDOR_FREESCALE),
		NAME_ELEMENT(RTI_VENDOR_OKI),
		NAME_ELEMENT(RTI_VENDOR_TEXAS_INSTRUMENTS)
};

const char * const rtiDevType_list[RTI_DEVICE_TARGET_TYPE_END] =
{
		[0 ... (RTI_DEVICE_TARGET_TYPE_END - 1)] = NULL,
		NAME_ELEMENT(RTI_DEVICE_RESERVED_INVALID),			//0x00
        NAME_ELEMENT(RTI_DEVICE_REMOTE_CONTROL),			//0x01
        NAME_ELEMENT(RTI_DEVICE_TARGET_TYPE_START),			//0x02
        NAME_ELEMENT(RTI_DEVICE_TELEVISION),				//0x02
        NAME_ELEMENT(RTI_DEVICE_PROJECTOR),					//0x03
        NAME_ELEMENT(RTI_DEVICE_PLAYER),					//0x04
        NAME_ELEMENT(RTI_DEVICE_RECORDER),					//0x05
        NAME_ELEMENT(RTI_DEVICE_VIDEO_PLAYER_RECORDER),		//0x06
        NAME_ELEMENT(RTI_DEVICE_AUDIO_PLAYER_RECORDER),		//0x07
        NAME_ELEMENT(RTI_DEVICE_AUDIO_VIDEO_RECORDER),		//0x08
        NAME_ELEMENT(RTI_DEVICE_SET_TOP_BOX),				//0x09
        NAME_ELEMENT(RTI_DEVICE_HOME_THEATER_SYSTEM),		//0x0A
        NAME_ELEMENT(RTI_DEVICE_MEDIA_CENTER_PC),			//0x0B
        NAME_ELEMENT(RTI_DEVICE_GAME_CONSOLE),				//0x0C
        NAME_ELEMENT(RTI_DEVICE_SATELLITE_RADIO_RECEIVER),	//0x0D
        NAME_ELEMENT(RTI_DEVICE_IR_EXTENDER),				//0x0E
        NAME_ELEMENT(RTI_DEVICE_MONITOR)					//0x0F
};

const char * const profile_list[RTI_PROFILE_ID_STD_END + 1] =
		{ [0 ... 2] = NULL, NAME_ELEMENT(RTI_PROFILE_ZRC),
				NAME_ELEMENT(RTI_PROFILE_ZID), };

const char * const vendor_list[7 + 1] = { //7 Elements for now
		[0 ... 7] = NULL, NAME_ELEMENT(RTI_VENDOR_TEXAS_INSTRUMENTS),
		//NAME_ELEMENT(RTI_PROFILE_ZID),
		};

const char * const Command_list[5 + 1] =
{ //5 Elements for now
		[0 ... 3] = NULL,
		NAME_ELEMENT(RTI_CERC_USER_CONTROL_PRESSED),
		NAME_ELEMENT(RTI_CERC_USER_CONTROL_REPEATED),
		NAME_ELEMENT(RTI_CERC_USER_CONTROL_RELEASED),
		NAME_ELEMENT(RTI_CERC_COMMAND_DISCOVERY_REQUEST),
		NAME_ELEMENT(RTI_CERC_COMMAND_DISCOVERY_RESPONSE)
};

const char * const AppState_list[AP_STATE_READY + 1] = { //Application States
		[0 ... AP_STATE_READY] = NULL,
		NAME_ELEMENT(AP_STATE_INIT),
		NAME_ELEMENT(AP_STATE_INIT_COLD),
		NAME_ELEMENT(AP_STATE_RESET),
		NAME_ELEMENT(AP_STATE_PAIR),
		NAME_ELEMENT(AP_STATE_VALIDATION),
		NAME_ELEMENT(AP_STATE_LATENCY_TEST_MODE),
		NAME_ELEMENT(AP_STATE_UNPAIR),
		NAME_ELEMENT(AP_STATE_NDATA),
		NAME_ELEMENT(AP_STATE_NDATA_PREPARE),
		NAME_ELEMENT(AP_STATE_WAIT_WAKEUP_FOR_PAIR),
		NAME_ELEMENT(AP_STATE_WAIT_WAKEUP_FOR_UNPAIR),
		NAME_ELEMENT(AP_STATE_WAIT_WAKEUP_FOR_NDATA),
		NAME_ELEMENT(AP_STATE_READY)
};

const char * const ZRC_Key_list[255 + 1] =
{ //255 Elements for now
		[0 ... 255] = NULL,
		NAME_ELEMENT(RTI_CERC_NUM_1),
		NAME_ELEMENT(RTI_CERC_NUM_2),
		NAME_ELEMENT(RTI_CERC_NUM_3),
		NAME_ELEMENT(RTI_CERC_NUM_4),
		NAME_ELEMENT(RTI_CERC_NUM_5),
		NAME_ELEMENT(RTI_CERC_NUM_6),
		NAME_ELEMENT(RTI_CERC_NUM_6),
		NAME_ELEMENT(RTI_CERC_NUM_7),
		NAME_ELEMENT(RTI_CERC_NUM_8),
		NAME_ELEMENT(RTI_CERC_NUM_9),
		NAME_ELEMENT(RTI_CERC_NUM_0),
		NAME_ELEMENT(RTI_CERC_SELECT),
		NAME_ELEMENT(RTI_CERC_UP),
		NAME_ELEMENT(RTI_CERC_DOWN),
		NAME_ELEMENT(RTI_CERC_LEFT),
		NAME_ELEMENT(RTI_CERC_RIGHT),
		NAME_ELEMENT(RTI_CERC_RIGHT_UP),
		NAME_ELEMENT(RTI_CERC_RIGHT_DOWN),
		NAME_ELEMENT(RTI_CERC_LEFT_UP),
		NAME_ELEMENT(RTI_CERC_LEFT_DOWN),
		NAME_ELEMENT(RTI_CERC_ROOT_MENU),
		NAME_ELEMENT(RTI_CERC_SETUP_MENU),
		NAME_ELEMENT(RTI_CERC_CONTENTS_MENU),
		NAME_ELEMENT(RTI_CERC_FAVORITE_MENU),
		NAME_ELEMENT(RTI_CERC_EXIT),
		NAME_ELEMENT(RTI_CERC_NUM_11),
		NAME_ELEMENT(RTI_CERC_NUM_12),
		NAME_ELEMENT(RTI_CERC_NUM_2),
		NAME_ELEMENT(RTI_CERC_NUM_1),
		NAME_ELEMENT(RTI_CERC_NUM_0),
		NAME_ELEMENT(RTI_CERC_NUM_3),
		NAME_ELEMENT(RTI_CERC_NUM_4),
		NAME_ELEMENT(RTI_CERC_NUM_5),
		NAME_ELEMENT(RTI_CERC_NUM_6),
		NAME_ELEMENT(RTI_CERC_NUM_7),
		NAME_ELEMENT(RTI_CERC_NUM_8),
		NAME_ELEMENT(RTI_CERC_NUM_9),
		NAME_ELEMENT(RTI_CERC_DOT),
		NAME_ELEMENT(RTI_CERC_ENTER),
		NAME_ELEMENT(RTI_CERC_CLEAR),
		NAME_ELEMENT(RTI_CERC_NEXT_FAVORITE),
		NAME_ELEMENT(RTI_CERC_CHANNEL_UP),
		NAME_ELEMENT(RTI_CERC_CHANNEL_DOWN),
		NAME_ELEMENT(RTI_CERC_PREVIOUS_CHANNEL),
		NAME_ELEMENT(RTI_CERC_SOUND_SELECT),
		NAME_ELEMENT(RTI_CERC_INPUT_SELECT),
		NAME_ELEMENT(RTI_CERC_DISPLAY_INFORMATION),
		NAME_ELEMENT(RTI_CERC_HELP),
		NAME_ELEMENT(RTI_CERC_PAGE_UP),
		NAME_ELEMENT(RTI_CERC_PAGE_DOWN),
		NAME_ELEMENT(RTI_CERC_POWER),
		NAME_ELEMENT(RTI_CERC_VOLUME_UP),
		NAME_ELEMENT(RTI_CERC_VOLUME_DOWN),
		NAME_ELEMENT(RTI_CERC_MUTE),
		NAME_ELEMENT(RTI_CERC_PLAY),
		NAME_ELEMENT(RTI_CERC_STOP),
		NAME_ELEMENT(RTI_CERC_PAUSE),
		NAME_ELEMENT(RTI_CERC_RECORD),
		NAME_ELEMENT(RTI_CERC_REWIND),
		NAME_ELEMENT(RTI_CERC_FAST_FORWARD),
		NAME_ELEMENT(RTI_CERC_EJECT),
		NAME_ELEMENT(RTI_CERC_FORWARD),
		NAME_ELEMENT(RTI_CERC_BACKWARD),
		NAME_ELEMENT(RTI_CERC_STOP_RECORD),
		NAME_ELEMENT(RTI_CERC_PAUSE_RECORD),
		NAME_ELEMENT(RTI_CERC_ANGLE),
		NAME_ELEMENT(RTI_CERC_SUB_PICTURE),
		NAME_ELEMENT(RTI_CERC_VIDEO_ON_DEMAND),
		NAME_ELEMENT(RTI_CERC_ELECTRONIC_PROGRAM_GUIDE),
		NAME_ELEMENT(RTI_CERC_TIMER_PROGRAMMING),
		NAME_ELEMENT(RTI_CERC_INITIAL_CONFIGURATION),
		NAME_ELEMENT(RTI_CERC_PLAY_FUNCTION),
		NAME_ELEMENT(RTI_CERC_PAUSE_PLAY_FUNCTION),
		NAME_ELEMENT(RTI_CERC_RECORD_FUNCTION),
		NAME_ELEMENT(RTI_CERC_PAUSE_RECORD_FUNCTION),
		NAME_ELEMENT(RTI_CERC_STOP_FUNCTION),
		NAME_ELEMENT(RTI_CERC_MUTE_FUNCTION),
		NAME_ELEMENT(RTI_CERC_RESTORE_VOLUME_FUNCTION),
		NAME_ELEMENT(RTI_CERC_TUNE_FUNCTION),
		NAME_ELEMENT(RTI_CERC_SELECT_MEDIA_FUNCTION),
		NAME_ELEMENT(RTI_CERC_SELECT_AV_INPUT_FUNCTION),
		NAME_ELEMENT(RTI_CERC_SELECT_AUDIO_INPUT_FUNCTION),
		NAME_ELEMENT(RTI_CERC_POWER_TOGGLE_FUNCTION),
		NAME_ELEMENT(RTI_CERC_POWER_OFF_FUNCTION),
		NAME_ELEMENT(RTI_CERC_POWER_ON_FUNCTION),
		NAME_ELEMENT(RTI_CERC_F1_BLUE),
		NAME_ELEMENT(RTI_CERC_F2_RED),
		NAME_ELEMENT(RTI_CERC_F3_GREEN),
		NAME_ELEMENT(RTI_CERC_F4_YELLOW),
		NAME_ELEMENT(RTI_CERC_F5),
		NAME_ELEMENT(RTI_CERC_DATA),
		NAME_ELEMENT(RTI_CERC_RESERVED_1)
};

const char * const RNPpowerState_list[4 + 1] =
{ //4 Application States
		[0 ... 4] = NULL,
		NAME_ELEMENT(ZRC_APP_RNP_POWER_STATE_ACTIVE),
		NAME_ELEMENT(ZRC_APP_RNP_POWER_STATE_NPI_SLEEP),
		NAME_ELEMENT(ZRC_APP_RNP_POWER_STATE_STANDBY_ACTIVE),
		NAME_ELEMENT(ZRC_APP_RNP_POWER_STATE_STANDBY_SLEEP)
};

#endif //ZRC_APP_LOG_CONSTANTS_H
